//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.02 at 02:04:37 PM CEST 
//

package com.erioxyde.app.asg.bo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for itemType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_enabled"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_pressed"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_focused"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_hovered"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_checkable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_checked"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_activated"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_window_focused"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}state_selected"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = { "value" })
public class ItemType
{

  @XmlValue
  protected String value;

  @XmlAttribute(name = "state_enabled", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateEnabled;

  @XmlAttribute(name = "drawable", namespace = "http://schemas.android.com/apk/res/android")
  public String drawable;

  @XmlAttribute(name = "state_pressed", namespace = "http://schemas.android.com/apk/res/android")
  protected String statePressed;

  @XmlAttribute(name = "state_focused", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateFocused;

  @XmlAttribute(name = "state_hovered", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateHovered;

  @XmlAttribute(name = "state_checkable", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateCheckable;

  @XmlAttribute(name = "state_checked", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateChecked;

  @XmlAttribute(name = "state_activated", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateActivated;

  @XmlAttribute(name = "state_window_focused", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateWindowFocused;

  @XmlAttribute(name = "state_selected", namespace = "http://schemas.android.com/apk/res/android")
  protected String stateSelected;

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValue()
  {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setValue(String value)
  {
    this.value = value;
  }

  /**
   * Gets the value of the stateEnabled property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateEnabled()
  {
    return stateEnabled;
  }

  /**
   * Sets the value of the stateEnabled property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateEnabled(String value)
  {
    this.stateEnabled = value;
  }

  /**
   * Gets the value of the drawable property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDrawable()
  {
    return drawable;
  }

  /**
   * Sets the value of the drawable property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDrawable(String value)
  {
    this.drawable = value;
  }

  /**
   * Gets the value of the statePressed property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStatePressed()
  {
    return statePressed;
  }

  /**
   * Sets the value of the statePressed property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStatePressed(String value)
  {
    this.statePressed = value;
  }

  /**
   * Gets the value of the stateFocused property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateFocused()
  {
    return stateFocused;
  }

  /**
   * Sets the value of the stateFocused property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateFocused(String value)
  {
    this.stateFocused = value;
  }

  /**
   * Gets the value of the stateHovered property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateHovered()
  {
    return stateHovered;
  }

  /**
   * Sets the value of the stateHovered property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateHovered(String value)
  {
    this.stateHovered = value;
  }

  /**
   * Gets the value of the stateCheckable property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateCheckable()
  {
    return stateCheckable;
  }

  /**
   * Sets the value of the stateCheckable property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateCheckable(String value)
  {
    this.stateCheckable = value;
  }

  /**
   * Gets the value of the stateChecked property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateChecked()
  {
    return stateChecked;
  }

  /**
   * Sets the value of the stateChecked property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateChecked(String value)
  {
    this.stateChecked = value;
  }

  /**
   * Gets the value of the stateActivated property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateActivated()
  {
    return stateActivated;
  }

  /**
   * Sets the value of the stateActivated property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateActivated(String value)
  {
    this.stateActivated = value;
  }

  /**
   * Gets the value of the stateWindowFocused property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateWindowFocused()
  {
    return stateWindowFocused;
  }

  /**
   * Sets the value of the stateWindowFocused property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateWindowFocused(String value)
  {
    this.stateWindowFocused = value;
  }

  /**
   * Gets the value of the stateSelected property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStateSelected()
  {
    return stateSelected;
  }

  /**
   * Sets the value of the stateSelected property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStateSelected(String value)
  {
    this.stateSelected = value;
  }

}
